// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjovfdxvleudwianspyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb3ZmZHh2bGV1ZHdpYW5zcHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Nzk0MDMsImV4cCI6MjA3MTE1NTQwM30.FC29u5i3gezmHdOL4H0Ry89-x_RpZvT-vL95r2B5DTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});